### ISSUE TITLE
test default phenotypes are valid

### ISSUE THREAD

**Issue by jingchunzhu** [ucscXena/ucsc-xena-client#189]

**Comment by jingchunzhu** [comment]
write python script for test

**Comment by abhishekvermasg** [comment]
I want to work on this issue. Would be grateful for code pointers. Is there any IRC channel or gitter chat to reach the team easily? @acthp

**Comment by maryjgoldman** [comment]
See #188 for help.

**Comment by vdevgan** [comment]
I see this issue isn't closed. May I look into it? connect me to anyone who could get me more info.

**Comment by maryjgoldman** [comment]
It is similar to #188. Here is a comment from that issue with the references changed for the phenotypes rather than the datasets: 

We load some hand-curated metadata about the public datasets when the app launches. The url is here:

https://github.com/ucscXena/ucsc-xena-client/blob/master/js/xenaQuery.js#L406

We need a python script that will verify that all of these phenotype columns exist, to avoid errors during release. A naive way to do this would be to use the python API to fetch the dataset list for each cohort, and check that it includes the correct datasets for that cohort.

https://ucscpublic.xenahubs.net/docs/python/xena_query.py
