### ISSUE TITLE
Add p-values to spearman' rank and pearson's rho

### ISSUE THREAD

**Issue by maryjgoldman** [ucscXena/ucsc-xena-client#340]
This is in the chart view. Example: https://xenabrowser.net/heatmap/?bookmark=c0cdc6a6538227b856ad5954a991554a. Add p-values to these tests

**Comment by maryjgoldman** [comment]
Let user yomara.romero.l@upch.pe know when it is implemented

**Comment by madhavmk** [comment]
Could I take up this issue ?
Also, could you fill me up on any extra implementation details that I need to know.

**Comment by jingchunzhu** [comment]
Yes. Go ahead

**Comment by madhavmk** [comment]
Could you help me out with the study, first variable and second variable to help me replicate what is shown below.
https://xenabrowser.net/heatmap/?bookmark=c0cdc6a6538227b856ad5954a991554a

**Comment by madhavmk** [comment]
Some clarifications are needed..
1) Is it a 2 sided test or a 1 sided z-test? (I am assuming 2 sided)
2)Does it use sample standard deviation or population standard deviation? (I am assuming population deviation)

**Comment by jingchunzhu** [comment]
@madhavmk spearman' rank and pearson's rho are not z-test.

**Comment by jingchunzhu** [comment]
@madhavmk code related to this issue is here https://github.com/ucscXena/ucsc-xena-client/blob/master/js/chart.js#L1288

**Comment by madhavmk** [comment]
Please correct me if I am wrong.
I am calculating p value from a coefficient  by the following method.
1) Find "t" value with formula
    t = r * (sqrt(n-2)/(1-r^2))
2) Find corresponding p value for that "t" value with 2 tails and "n-2 degrees of freedom".

**Comment by jingchunzhu** [comment]
The above is correct.

**Comment by madhavmk** [comment]
![screenshot from 2019-03-03 13-16-03](https://user-images.githubusercontent.com/29497860/53692549-00e81f80-3db8-11e9-98a4-02170881707c.png)
Is this what is expected?

**Comment by madhavmk** [comment]
I have created a PR on this issue. I hope it's what was expected, but let me know if it needs modification.
PR number #388

**Comment by madhavmk** [comment]
@jingchunzhu  I have created a PR on this issue. I hope it's what was expected, but let me know if it needs modification.
PR number #388

**Comment by jingchunzhu** [comment]
@madhavmk It is good that you included a screenshot of the new results. Looking at it, it is odd that the two correlation methods have such different p values, one says the scatterplot is highly significant (e-98), the other p value says not significant (0.2).  Can you verify the p value results using an independent method, i.e. not jStats?

**Comment by madhavmk** [comment]
![screenshot from 2019-03-06 20-55-44](https://user-images.githubusercontent.com/29497860/53896285-b685cd80-4059-11e9-962b-9cb0a6cdd0ad.png)
![screenshot from 2019-03-06 20-56-08](https://user-images.githubusercontent.com/29497860/53896295-bbe31800-4059-11e9-99d4-04d6f4e10f84.png)
![screenshot from 2019-03-06 20-56-54](https://user-images.githubusercontent.com/29497860/53896309-bf769f00-4059-11e9-9cf9-b50cc6c96f87.png)
@jingchunzhu I have calculated the p values from the coefficients with Excel as well. The orders of both answers match exactly while the exact values slightly differ since I made Excel use the coefficient value only upto 4 decimal points while the xena-client uses the exact floating point of coefficient values.
The p value in xena-client is calculated correctly.

**Comment by madhavmk** [comment]
@jingchunzhu Is there anything wrong in in the screen-shots above? If any further changes have to be made, please inform me, and I will update my PR accordingly.

**Comment by madhavmk** [comment]
@jingchunzhu  I have updated the PR to reflect the formatting changes you requested. #388

**Comment by jingchunzhu** [comment]
@madhavmk  please see this: https://xenabrowser.net/heatmap/?bookmark=1172b2d33c85af19e5c3cb3816eaed17  p value is NaN (not a number), please fix it.

**Comment by madhavmk** [comment]
@jingchunzhu This is becaue when calculating t value using " t = r * (sqrt(n-2)/(1-r^2)) ", the "1-r^2" becomes 0 and the t value tends to infinity( NaN because zero division not allowed). This means that the p value from t=infinity is very insignificant (becomes zero). So, I will format it such that 'p=0' is given as output in cases like this. Please tell me if my methodology is correct and if any changes should be made.

**Comment by madhavmk** [comment]
@jingchunzhu  I have created a new PR #402  to fix the above issue. Do any changes have to be made?
