### ISSUE TITLE
Use WithoutGeneModel method for "probes"

### ISSUE THREAD

**Issue by NoopDog** [ucscXena/ucsc-xena-client#380]
Also, I suspect 'probes' should be WithoutGeneModel. We can't pull a gene model for a list of probes, since they are not spatially related: they're just random locations across the genome

**Comment by NoopDog** [comment]
@acthp @jingchunzhu can we get a test case for this and decide if this needs to be changed or not? Thanks!

**Comment by jingchunzhu** [comment]
test case: http://cc.xenabrowser.net/heatmap/?bookmark=725dee8c6ee6e67fd6a10bdfcfd86770 column E.  From the UI, column E functions fine. There is no gene model displayed on top. You click and drag in the typical gene model area does not trigger anything for the user.

**Comment by NoopDog** [comment]
@acthp @MillenniumFalconMechanic  is there any work to do on this one?

**Comment by acthp** [comment]
So, this issue is kind of a modeling bug which doesn't create any observable error in the UI. There are two 'direction' methods, directionWithGeneModel and directionWithoutGeneModel. 'genes' and 'probes' columns have no gene model, but 'probes' is configured to use directionWithGeneModel. So, bug, right?

But you can't actually invoke the bug, because directionWithGeneModel will only do a gene model operation if it is called from the handler for the gene model annotation (zone 'a'). Since there's no gene model annotation for 'probes', it never hits this code.

So, it's really just a confusion in the code. We could a) make 'probes' use directionWithoutGeneModel, for consistency, or b) drop directionWithoutGeneModel, because it's not doing anything: the 'zone' already dispatches to the correct method.

I suggest 'b'.

**Comment by NoopDog** [comment]
HI @acthp is this ok to close? Thx.
