### ISSUE TITLE
tooltip needs a close button

### ISSUE THREAD

**Issue by jingchunzhu** [ucscXena/ucsc-xena-client#45]
the current "alt-click to unfreeze" requires alt-click on the visual map itself. I often try to alt-click on the tooltip itself.

**Comment by achang28** [comment]
Assigned to me.  Experienced the issue myself

**Comment by david4096** [comment]
I'm experiencing a problem with the tooltips, at least on FF 54.0 (64-bit).

Sometimes the lock doesn't happen properly, guessing something is up with the ctrl-click capture? If I don't move my mouse and double ctrl-click I can get the tooltip to lock. Unlocking can take several ctrl-clicks.

**Comment by acthp** [comment]
@david4096 Can't repro on FF 54.0 ubuntu. You're on OSX? Is it consistent, or dependent on the data in view?

**Comment by david4096** [comment]
I'm playing at this page:

https://xenabrowser.net/heatmap/

You can observe the disappearing mouse. This screen recorder doesn't show the first mouse click, but it's there and I can still reproduce.

[out-2.ogv.tar.gz](https://github.com/ucscXena/ucsc-xena-client/files/1519316/out-2.ogv.tar.gz)

I find it confusing to have "tooltips" that come from mouse hover, and "helper tooltips" that can pop up here and there. Could the reticle output be handled in an inline component without breaking the design patterns? Instead of locking data points, maybe you could "bookmark data point", and then have those navigable in a component.

**Comment by david4096** [comment]
I tried opening up another public hub and observed similar behavior. You can see where I spam ctrl-click to unlock the tooltip.

[out-4.ogv.tar.gz](https://github.com/ucscXena/ucsc-xena-client/files/1519389/out-4.ogv.tar.gz)

**Comment by acthp** [comment]
I may have to debug this in-person. Still can't reproduce it, even on the same bookmark. It's like something else is capturing the events.

I did pitch a data-picker UI at some point, instead of 'freeze tooltip', but didn't get any interest. Might be worth doing a proof-of-concept.
